### ISSUE TITLE
RethinkDb connection is closing 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1031]
The connection to RethinkDb gets closed. This has happened on one other occasion in the last month. 

I checked through the last set of logs on production, and only the factoid app has a problem after being up for ~12 days (Dec 20 - Jan 1)

```
...
[36mwebapp        |[0m 2022-01-01T04:08:28.608168825Z [32minfo[39m:    [0mGET /api/document?limit=20&offset=120 [0m- [0m- ms - -[0m
[36mwebapp        |[0m 2022-01-01T04:08:28.608174766Z [32minfo[39m:    [0mGET /api/document/zip [31m504 [0m143656.568 ms - 142[0m
[36mwebapp        |[0m 2022-01-01T04:08:28.622115287Z HTTPStatusError: Gateway Time-out (504)
[36mwebapp        |[0m 2022-01-01T04:08:28.622150527Z     at checkHTTPStatus (/home/appuser/app/src/util/fetch.js:27:11)
[36mwebapp        |[0m 2022-01-01T04:08:28.622156072Z     at runMicrotasks (<anonymous>)
[36mwebapp        |[0m 2022-01-01T04:08:28.622160817Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[36mwebapp        |[0m 2022-01-01T04:08:28.622657050Z HTTPStatusError: Gateway Time-out (504)
[36mwebapp        |[0m 2022-01-01T04:08:28.622676849Z     at checkHTTPStatus (/home/appuser/app/src/util/fetch.js:27:11)
[36mwebapp        |[0m 2022-01-01T04:08:28.622681886Z     at runMicrotasks (<anonymous>)
[36mwebapp        |[0m 2022-01-01T04:08:28.622686561Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[36mwebapp        |[0m 2022-01-01T04:08:28.622855367Z HTTPStatusError: Gateway Time-out (504)
[36mwebapp        |[0m 2022-01-01T04:08:28.622870180Z     at checkHTTPStatus (/home/appuser/app/src/util/fetch.js:27:11)
[36mwebapp        |[0m 2022-01-01T04:08:28.622875125Z     at runMicrotasks (<anonymous>)
[36mwebapp        |[0m 2022-01-01T04:08:28.622879749Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[36mwebapp        |[0m 2022-01-01T04:08:28.644707010Z ReqlRuntimeError: Connection is closed in:
[36mwebapp        |[0m 2022-01-01T04:08:28.644764119Z r.db("factoid").table("document").filter(r.row("secret").ne("demo")).orderBy(r.desc(r.branch(r.row("createdDate").typeOf().eq("STRING"), r.ISO8601(r.row("createdDate")), r.row("createdDate").typeOf().eq("NUMBER"), r.epochTime(r.row("createdDate")), r.row("createdDate")))).count()
[36mwebapp        |[0m 2022-01-01T04:08:28.644772773Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mwebapp        |[0m 2022-01-01T04:08:28.644799968Z     at ReqlRuntimeError.ReqlError [as constructor] (/home/appuser/app/node_modules/rethinkdb/errors.js:23:13)
[36mwebapp        |[0m 2022-01-01T04:08:28.644804425Z     at new ReqlRuntimeError (/home/appuser/app/node_modules/rethinkdb/errors.js:90:51)
[36mwebapp        |[0m 2022-01-01T04:08:28.644808034Z     at mkErr (/home/appuser/app/node_modules/rethinkdb/util.js:177:10)
...
```

I can't yet reproduce this locally, but trying to figure it out....

**Comment by maxkfranz** [comment]
Likely: GET /api/document

https://github.com/PathwayCommons/factoid/blob/unstable/src/server/routes/api/document/index.js#L1235

This may be a deployment/docker issue, so you may have to run the docker containers locally to reproduce it.

Are there any errors in the rethink container itself?

**Comment by jvwong** [comment]
Here's all the logs for the db, it has been running since dec 7:

```
db            | 2021-12-07T14:18:54.548307619Z Running rethinkdb 2.3.7~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))...
db            | 2021-12-07T14:18:54.559411443Z Running on Linux 5.4.0-77-generic x86_64
db            | 2021-12-07T14:18:54.559439407Z Loading data from directory /data/rethinkdb_data
db            | 2021-12-07T14:18:54.586823830Z Listening for intracluster connections on port 29015
db            | 2021-12-07T14:18:54.816413645Z Listening for client driver connections on port 28015
db            | 2021-12-07T14:18:54.817679259Z Listening for administrative HTTP connections on port 8080
db            | 2021-12-07T14:18:54.818179717Z Listening on cluster addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-07T14:18:54.818830052Z Listening on driver addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-07T14:18:54.819314316Z Listening on http addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-07T14:18:54.819810918Z Server ready, "6327411a3cfe_dyu" 7a8238c9-5194-4396-8bd5-3e94e16c7336
db            | 2021-12-07T14:18:55.060746041Z A newer version of the RethinkDB server is available: 2.4.0. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.
db            | 2021-12-19T16:27:24.264031121Z Running rethinkdb 2.3.7~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))...
db            | 2021-12-19T16:27:24.279763855Z Running on Linux 5.4.0-77-generic x86_64
db            | 2021-12-19T16:27:24.279807735Z Loading data from directory /data/rethinkdb_data
db            | 2021-12-19T16:27:24.323253206Z Listening for intracluster connections on port 29015
db            | 2021-12-19T16:27:24.520289998Z Listening for client driver connections on port 28015
db            | 2021-12-19T16:27:24.522725162Z Listening for administrative HTTP connections on port 8080
db            | 2021-12-19T16:27:24.523004152Z Listening on cluster addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-19T16:27:24.523604503Z Listening on driver addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-19T16:27:24.523747177Z Listening on http addresses: 127.0.0.1, 172.21.0.5
db            | 2021-12-19T16:27:24.523981203Z Server ready, "6327411a3cfe_dyu" 7a8238c9-5194-4396-8bd5-3e94e16c7336
db            | 2021-12-19T16:27:24.630344572Z A newer version of the RethinkDB server is available: 2.4.0. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.
db            | 2022-01-01T04:08:30.379042781Z Running rethinkdb 2.3.7~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))...
db            | 2022-01-01T04:08:30.389588534Z Running on Linux 5.4.0-77-generic x86_64
db            | 2022-01-01T04:08:30.389730345Z Loading data from directory /data/rethinkdb_data
db            | 2022-01-01T04:08:30.430192673Z Listening for intracluster connections on port 29015
db            | 2022-01-01T04:08:30.686071799Z Listening for client driver connections on port 28015
db            | 2022-01-01T04:08:30.687385377Z Listening for administrative HTTP connections on port 8080
db            | 2022-01-01T04:08:30.688373641Z Listening on cluster addresses: 127.0.0.1, 172.21.0.5
db            | 2022-01-01T04:08:30.688932958Z Listening on driver addresses: 127.0.0.1, 172.21.0.5
db            | 2022-01-01T04:08:30.689117691Z Listening on http addresses: 127.0.0.1, 172.21.0.5
db            | 2022-01-01T04:08:30.689291483Z Server ready, "6327411a3cfe_dyu" 7a8238c9-5194-4396-8bd5-3e94e16c7336
db            | 2022-01-01T04:08:30.839268389Z A newer version of the RethinkDB server is available: 2.4.0. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.
```

It looks like it may have restarted at the fail time for the webapp?

**Comment by jvwong** [comment]
Looking at the containers with `docker ps` I can see the rethinkdb container restarted:

```
CONTAINER ID   IMAGE    COMMAND    CREATED        STATUS        PORTS   NAMES
...   rethinkdb:2.3.7   "rethinkdb --bind all"   3 weeks ago    Up 2 days     8080/tcp, 28015/tcp, 29015/tcp                                             db
```

**Comment by jvwong** [comment]
Maybe RethinkDB container is being killed off, possibly due to memory issues based on three pieces of evidence:

1. [RethinkDB: Crash Recovery](https://rethinkdb.com/docs/crashes/)

Running `sudo dmesg` on the production Droplet prints out two `Out of memory: Killed process 1012521` statements, which point to an out of memory crash at
  - Sun Dec 19 16:26:50 2021
  - Sat Jan  1 04:07:53 2022

2.  The RethinkDB logs above show container restarts at around
  - 2021-12-19T16:27:24.264031121Z
  - 2022-01-01T04:08:30.379042781Z

3. The Droplet data logs (only go back 14 days) but show a  memory useage spike on Jan 1


<img width="999" alt="Screen Shot 2022-01-03 at 2 39 24 PM" src="https://user-images.githubusercontent.com/4706307/147975754-0616d8f8-1dcd-4d06-a399-0762d9ad18ef.png">

Note: [Runtime options with Memory, CPUs, and GPUs](https://docs.docker.com/config/containers/resource_constraints/)

**Comment by maxkfranz** [comment]
Simple things that may help with this:

(1) Increase the memory allocated to the DB container.

(2) Set an index in RethinkDB on the date field, since we're searching by date.

(3) Cache the recent factoids: https://github.com/PathwayCommons/factoid/issues/909


(1) and (2) may be sufficient without (3).
