### ISSUE TITLE
Filtering REACH text mining results

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#145]
The REACH results provides many entities, often not involved in an interaction. This has the result of cluttering and obscuring the display.

Suggestion is to 

1. Filter entities for those involved in interactions
2. Merge entities

**Comment by jvwong** [comment]
I'm getting no response/errors on my prelim test passages [google doc](https://docs.google.com/document/d/1voXzUuU4sjmtTsQTlpbIHMFswxOthHU37ArdOJVSla0/edit#heading=h.8e4o3n9sxg0n). 

e.g. breaking case: 

>The Fas family of cell surface receptors initiate the apototic (sic) pathway through interaction with the external ligand, FasL. The cytoplasmic domain of Fas interacts with a number of molecules in the transduction of the external signal to the cytoplasmic side of the cell membrane. The most notable cytoplasmic domain is the Death Domain (DD) that is involved in recruiting the FAS-associating death domain-containing protein (FADD). This interaction drives downstream events.

console: 
```js
Unhandled rejection TypeError: Cannot read property 'namespace' of undefined
    at groundIsSame (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:54:40)
    at groundReachMap.forEach (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:74:17)
    at Map.forEach (native)
    at addElement (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:73:26)
    at entFrames.forEach.frame (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:126:9)
    at Array.forEach (native)
    at makeDocJson (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:103:17)
From previous event:
    at Object.get (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:206:54)
    at fillDoc (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/index.js:41:19)
    at Promise.try.then.then.doc (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/index.js:97:21)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at /Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/index.js:97:8
    at Layer.handle [as handle_request] (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:317:13)
    at /Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:317:13)
    at /Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/cookie-parser/index.js:56:14)
    at Layer.handle [as handle_request] (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:317:13)
    at /Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/express/lib/router/index.js:284:7
```

![screenshot at sep 12 09-03-31](https://user-images.githubusercontent.com/4706307/30327219-46998684-9799-11e7-8783-e5286ab136a3.png)
