### ISSUE TITLE
Text processing step freeze/fail 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#164]
Freezes (master) or long delay with failure (unstable) to generate populated doc link. Reach (local) web service is working OK.

Breaking case: 

- Input text
> The Fas family of cell surface receptors initiate the apoptotic pathway through interaction with the external ligand, FasL. The cytoplasmic domain of Fas interacts with a number of molecules in the transduction of the external signal to the cytoplasmic side of the cell membrane. The most notable cytoplasmic domain is the Death Domain (DD) that is involved in recruiting the FAS-associating death domain-containing protein (FADD).

- Client
![factoid_error_fas](https://user-images.githubusercontent.com/4706307/34726582-7c0c5bf2-f522-11e7-94bc-934356d256a2.png)

- Server

```js
info:    GET /document/0fc8b9eb-9566-42fb-9851-3f83764e0d5e/b86d44df-fef8-4203-aa4c-b7e7d83e6dc5 200 3.394 ms - 827
info:    GET /deps.css 304 1.652 ms - -
info:    GET /bundle.css 304 1.950 ms - -
info:    GET /deps.js 304 0.381 ms - -
info:    GET /bundle.js 304 0.294 ms - -
info:    GET / 304 3.296 ms - -
info:    GET /bundle.css 200 3.145 ms - 34182
info:    GET /deps.css 200 4.574 ms - 339563
info:    GET /bundle.js 200 3.647 ms - 734902
info:    GET /deps.js 200 3.033 ms - 9508348
info:    GET /icon.png 200 2.268 ms - 13792
Unhandled rejection TypeError: Cannot read property 'entry' of undefined
    at processXml (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/element-association/uniprot.js:157:30)
    at tryCatcher (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)

{ type: 'chemical',
  namespace: 'pubchem',
  id: 471583,
  name: '(2S)-2-[[(2S)-2-amino-3-carboxypropanoyl]amino]butanedioic acid',
  inchi: 'InChI=1S/C8H12N2O7/c9-3(1-5(11)12)7(15)10-4(8(16)17)2-6(13)14/h3-4H,1-2,9H2,(H,10,15)(H,11,12)(H,13,14)(H,16,17)/t3-,4-/m0/s1',
  inchiKey: 'FRYULLIZUDQONW-IMJSIDKUSA-N',
  charge: 0,
  mass: 248.191,
  monoisotopicMass: 248.064,
  synonyms:
   [ 'Asp-Asp',
     'H-ASP-ASP-OH',
     'L-Asp-L-Asp',
     '58471-53-7',
     'CHEMBL17171',
     '(S)-2-((S)-2-Amino-3-carboxypropanamido)succinic acid',
     'CHEBI:73446',
     'L-alpha-aspartyl-L-aspartic acid',
     'D-D',
     'DD',
     'Asp-Asp-OH',
     'AC1LANFO',
     'NH2-Asp-Asp-COOH',
     'alpha-aspartylaspartic acid',
     'SCHEMBL434560',
     'FRYULLIZUDQONW-IMJSIDKUSA-N',
     '108867-30-7',
     'ZINC1575288',
     'BDBM50169127',
     'MFCD00055820',
     'AKOS025405021',
     'AK175092',
     '2-(2-Amino-3-carboxy-propionylamino)-succinic acid',
     '(S)-2-((S)-2-Amino-3-carboxy-propionylamino)-succinic acid',
     '(2S)-2-[[(2S)-2-amino-4-hydroxy-4-oxobutanoyl]amino]butanedioic acid' ],
  formulae: [ 'C8H12N2O7' ] }
info:    POST /api/document - - ms - -
```

**Comment by maxkfranz** [comment]
I've tracked this down to this entity: http://www.uniprot.org/locations/SL-0039

It's under the grounding namespace `'uniprot'`, so the reach doc-populating service tried to fill it as protein.  Reach itself types it as `'cellular-component'`

It looks like uniprot supports getting data for locations, e.g. http://www.uniprot.org/locations/SL-0039.rdf

Similarly, you can query getting an rdf result: http://www.uniprot.org/locations/?query=cell+membrane&format=rdf

However, none of this seems to be documented explicitly by uniprot.  I just read the source.

For now, the following should suffice for this issue: Restrict entity type used by Factoid to match grounding capabilities #168
