### ISSUE TITLE
Error on text input: Unhandled rejection TypeError: Cannot read property 'entry' of undefined

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#179]
Trying to fill a document with text (/new-document/fill) (master branch)

This input works: 
> p21 inactivates the CyclinE:Cdk2 complex, which prevents entry into S-phase of the cell cycle.

But this input doesn't: 
> p21 inactivates the complex of CyclinE1 with Cdk2, which prevents entry into S-phase of the cell cycle.

Trace:
```js
info:    GET / 304 0.703 ms - -
info:    POST /api/document - - ms - -
info:    GET /deps.css 304 2.424 ms - -
info:    GET /bundle.css 304 1.218 ms - -
info:    GET /deps.js 304 0.375 ms - -
info:    GET /bundle.js 304 0.486 ms - -
info:    GET /icon.png 304 0.332 ms - -
Unhandled rejection TypeError: Cannot read property 'entry' of undefined
    at processXml (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/element-association/uniprot.js:157:30)
    at tryCatcher (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by maxkfranz** [comment]
Reach returns erroneous information for Cyclin-E: 

```
{
				"text": "CyclinE1",
				"frame-id": "ment-api3405-UAZ-r1-Reach-0-18304",
				"type": "protein",
				"frame-type": "entity-mention",
				"end-pos": {
					"reference": "pass-api3405-UAZ-r1-Reach",
					"offset": 39,
					"object-type": "relative-pos"
				},
				"xrefs": [
					{
						"namespace": "uniprot",
						"species": "african clawed frog",
						"object-type": "db-reference",
						"id": "Q91780"
					}
				],
				"object-type": "frame",
				"start-pos": {
					"reference": "pass-api3405-UAZ-r1-Reach",
					"offset": 31,
					"object-type": "relative-pos"
				},
				"sentence": "sent-api3405-UAZ-r1-Reach-0",
				"alt-xrefs": [
					{
						"namespace": "uniprot",
						"species": "african clawed frog",
						"object-type": "db-reference",
						"id": "Q91780"
					},
					{
						"namespace": "uniprot",
						"species": "xenopus laevis",
						"object-type": "db-reference",
						"id": "Q91780"
					}
				]
			},
```

The organism is way off.

**Comment by jvwong** [comment]
Is it the species that is triggering the error? xenopus laevis isn't that crazy of a guess.

**Comment by maxkfranz** [comment]
Everything else is human, and reach doesn't give human proteins that are partial matches -- even just an alt xref.

I tried filtering out results that have bad organisms xrefs, but apparently reach doesn't consistently label organisms.  Sometimes an xref says 'human', and other times it says 'homo sapiens'.

Right now I'm just letting uniprot fail for bad inputs from reach.

**Comment by sacdallago** [comment]
Thanks @jvwong for debugging this. 

Thanks @maxkfranz for fixing this so quickly. Please, for the next time: let's use the PR practice, although ridiculous for small fixes it enforces good practice for all developers and makes it easier to understand who is working on what :)

I understand that this is a problem we should bring up to the REACH people? Implementing dictionaries that match flavors of organisms here seems out of scope. Opinions?
