### ISSUE TITLE
Factoid DB already exists

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#215]
## Environment info

- Browser version (client) : 65.0.3325.162
- Node.js version (server) :9.8.4

## Current (buggy) behaviour

1. run rethinkdb
2. run ```npm run watch```
3. the following error occurs:
```sh
Unhandled rejection ReqlOpFailedError: Database `factoid` already exists in:
r.dbCreate("factoid")
^^^^^^^^^^^^^^^^^^^^^
    at ReqlOpFailedError.ReqlError [as constructor] (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/errors.js:23:13)
    at ReqlOpFailedError.ReqlRuntimeError [as constructor] (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/errors.js:90:51)
    at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/errors.js:167:56)
    at new ReqlOpFailedError (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/errors.js:178:52)
    at mkErr (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/net.js:152:16)
    at TcpConnection.Connection._data (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/net.js:122:12)
    at Socket.<anonymous> (/Users/dylanfong/Documents/workspace/work/pc/factoid/node_modules/rethinkdb/net.js:689:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

```

## Desired behaviour

Not throw an error if the database already exists?

**Comment by d2fong** [comment]
But this doesn't happen on latest node so I guess we should just force everyone to always use the latest version of node?

**Comment by maxkfranz** [comment]
It's probably an error in the rdb driver w.r.t. the node version.  Maybe try node@8 and rdb latest?

Might also want to update the rdb driver lib for node if possible.

**Comment by maxkfranz** [comment]
The error you have is only printed if the server detects no existing db and so tries to create one.  The error is that the db actually does exist.  Either the first check was erroneous or you may have multiple instances starting at once -- creating a race condition.

**Comment by maxkfranz** [comment]
For the second case, nodemon may be suspect.
