### ISSUE TITLE
Reach fails on "Since our results demonstrated that Hzf binds to p53 and differentially modulates expression levels of the p53"

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#222]
## Environment info

- Browser version (client) : Version 65.0.3325.162 (Official Build) (64-bit)
- Node.js version (server) : 8.8.1

## Current (buggy) behaviour

The debug page hangs on (full) text entry.

## Desired behaviour

The page should return a link to the editor.

## Minimum steps to reproduce

Breaking case:

[das_cell_v24_2007.txt](https://github.com/PathwayCommons/factoid/files/1826631/das_cell_v24_2007.txt)

In fact, just this passage gives the same behaviour:

> Since our results demonstrated that Hzf binds to p53 and differentially modulates expression levels of the p53

But this passage is OK:

> Since our results demonstrated that Hzf binds to p53 and differentially modulates expression levels of the

Node stack trace:

```js
info:    GET /debug/new-document/fill 304 3.087 ms - -
info:    GET /deps.css 304 5.058 ms - -
info:    GET /bundle.css 304 0.522 ms - -
info:    GET /deps.js 304 0.520 ms - -
info:    GET /bundle.js 304 0.376 ms - -
info:    POST /api/document - - ms - -
Unhandled rejection TypeError: Cannot read property 'frame-type' of undefined
    at frameIsEntity (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:57:41)
    at Array.some (<anonymous>)
    at evtFrames.forEach.frame (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:209:44)
    at Array.forEach (<anonymous>)
    at makeDocJson (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/src/server/routes/api/document/reach.js:200:17)
    at tryCatcher (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jeffreywong/Projects/PathwayCommons/web/factoid/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```
I used the same text file with /api/uploadFile endpoint using Insomnia and it gave me back good results.

**Comment by maxkfranz** [comment]
This event frame is inconsistent:

```
{
  "frame-id": "evem-api37-UAZ-r1-Reach-0-661",
  "text": "Hzf binds to p53 and differentially modulates expression levels of the p53",
  "arguments": [
    {
      "text": "levels of the p53",
      "argument-type": "event",
      "type": "controlled",
      "object-type": "argument",
      "index": 0,
      "arg": "evem-api37-UAZ-r1-Reach-0-662"
    },
    {
      "text": "Hzf binds to p53",
      "argument-type": "complex",
      "type": "controller",
      "object-type": "argument",
      "index": 0,
      "args": {
        "theme1": "ment-api37-UAZ-r1-Reach-0-2769",
        "theme2": "ment-api37-UAZ-r1-Reach-0-2770"
      }
    }
  ],
  "type": "regulation",
  "frame-type": "event-mention",
  "subtype": "positive-regulation",
  "is-direct": false,
  "end-pos": {
    "reference": "pass-api37-UAZ-r1-Reach",
    "offset": 110,
    "object-type": "relative-pos"
  },
  "trigger": "modulates",
  "object-type": "frame",
  "start-pos": {
    "reference": "pass-api37-UAZ-r1-Reach",
    "offset": 36,
    "object-type": "relative-pos"
  },
  "sentence": "sent-api37-UAZ-r1-Reach-0",
  "found-by": "Positive_regulation_syntax_1_verb",
  "verbose-text": "Since our results demonstrated that Hzf binds to p53 and differentially modulates expression levels of the p53"
}

```

Note this part:

```
"args": {
  "theme1": "ment-api37-UAZ-r1-Reach-0-2769",
  "theme2": "ment-api37-UAZ-r1-Reach-0-2770"
}
```

We expect something like:

```
"arg": "evem-api37-UAZ-r1-Reach-0-662"
```

**Comment by d2fong** [comment]
Would it be useful to log this as an error if we could detect when reach
gives us stuff like this.

**Comment by maxkfranz** [comment]
@d2fong You already added general reach error logging, right?

**Comment by maxkfranz** [comment]
Re-assigning to @jvwong to confirm that other similar cases are OK.

**Comment by d2fong** [comment]
Yeah there should be general reach error logging

**Comment by maxkfranz** [comment]
Great, that should cover it for reproducibility for now.
