### ISSUE TITLE
Request for zip of data crashes server 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#813]
Upon requesting the zipped data at `/api/document/zip`, the NodeJS server crashes.

Notes:

```sh
Error: ENOENT: no such file or directory, open 'download/factoid_bulk.zip'
Emitted 'error' event at:
    at WriteStream.onerror (...factoid/node_modules/jszip/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at WriteStream.emit (events.js:198:13)
    at WriteStream.EventEmitter.emit (domain.js:448:20)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

```

**Comment by metincansiper** [comment]
@jvwong I created #818 to resolve this.
