### ISSUE TITLE
Network-related papers aren't being updated for particular doc

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#993]
Cannot updated the network-related papers,  with this particular doc/entities...

Document link: https://biofactoid.org/document/0d498284-39cd-48bb-bdcb-528ae36bdcb6

```
webapp_container | info:    Updating network-level related papers for doc 0d498284-39cd-48bb-bdcb-528ae36bdcb6
webapp_container | error:   Finding indra documents failed
webapp_container |  error:    TypeError: Cannot read property 'dbName' of null
```

**Comment by jvwong** [comment]
Another set of observations about above:

1. Doc was submitted, but didn't make it to the 'public' status
2. Explorer text for interaction  has unknown ('?') participant listed instead of GAS2L1
3. 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/4706307/123309675-38cc8100-d4f3-11eb-8b87-9bff12a9c4e0.png">

**Comment by jvwong** [comment]
After manual refresh via admin:

```
webapp_container | 2021-06-25T13:34:03.962599689Z error:   Finding indra documents failed
webapp_container | 2021-06-25T13:34:03.963296848Z error:    TypeError: Cannot read property 'dbName' of null
webapp_container | 2021-06-25T13:34:03.963347519Z     at getXref (src/server/routes/api/document/indra.js:110:20)
webapp_container | 2021-06-25T13:34:03.963354280Z     at getAgent (src/server/routes/api/document/indra.js:86:18)
webapp_container | 2021-06-25T13:34:03.963359792Z     at getForEl (src/server/routes/api/document/indra.js:137:19)
webapp_container | 2021-06-25T13:34:03.963380610Z     at src/server/routes/api/document/indra.js:262:53
webapp_container | 2021-06-25T13:34:03.963387068Z     at Array.map (<anonymous>)
webapp_container | 2021-06-25T13:34:03.963392628Z     at getDocuments (src/server/routes/api/document/indra.js:262:43)
webapp_container | 2021-06-25T13:34:03.963409940Z     at src/server/routes/api/document/indra.js:365:28
webapp_container | 2021-06-25T13:34:03.963416287Z     at runMicrotasks (<anonymous>)
webapp_container | 2021-06-25T13:34:03.963421853Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
webapp_container | 2021-06-25T13:34:03.963427348Z     at async getRelPprsForEl (src/server/routes/api/document/index.js:2261:22)
webapp_container | 2021-06-25T13:34:03.963432877Z     at async Promise.all (index 0)
webapp_container | 2021-06-25T13:34:03.963438182Z     at async getRelatedPapersForNetwork (src/server/routes/api/document/index.js:2276:7)
webapp_container | 2021-06-25T13:34:03.963443841Z     at async updateRelatedPapers (src/server/routes/api/document/index.js:2193:3)
webapp_container | 2021-06-25T13:34:03.963449480Z     at async updateDoc (src/server/routes/api/document/index.js:2052:13)
webapp_container | 2021-06-25T13:34:03.965742921Z error:   Error in getRelatedPapersForNetwork Cannot read property 'dbName' of null
```

**Comment by jvwong** [comment]
This one's a head scratcher. If you check out the [doc JSON](https://biofactoid.org/api/document/0d498284-39cd-48bb-bdcb-528ae36bdcb6) you can see a 'missing' node (`9db00e87-f6c8-4e84-b393-c10f4fc9445f`):

```json
{
  "id": "0d498284-39cd-48bb-bdcb-528ae36bdcb6",
  "secret": "read-only",
  "organisms": [
    "9606"
  ],
  "elements": [
    {
      "id": "9db00e87-f6c8-4e84-b393-c10f4fc9445f",
      "secret": "read-only",
      "position": {
        "x": 138.6042961674867,
        "y": 153.59361692482818
      },
      "name": "",
      "description": "",
      "type": "entity",
      "completed": false,
      "association": null
    },
...
}
```

So the related papers system tries to access the grounding etc to call INDRA but of course fails.

**Comment by jvwong** [comment]
This is the only case where this happens so will close unless it becomes a problem.
